# 请参考这个配置文件
#
app_name:
  development:
    app_id: <%= ENV['WECHAT_APP_NAME_APP_ID'] %>
    app_secret: <%= ENV['WECHAT_APP_NAME_APP_SECRET'] %>
    oauth2_redirect_uri: <%= ENV['WECHAT_APP_NAME_OAUTH2_REDIRECT_URI'] %>

  production:
    app_id: <%= ENV['WECHAT_APP_NAME_APP_ID'] %>
    app_secret: <%= ENV['WECHAT_APP_NAME_APP_SECRET'] %>
    oauth2_redirect_uri: <%= ENV['WECHAT_APP_NAME_OAUTH2_REDIRECT_URI'] %>

# 如果不需要多环境支持，也可以这样
app_name:
  app_id: <%= ENV['WECHAT_APP_NAME_APP_ID'] %>
  app_secret: <%= ENV['WECHAT_APP_NAME_APP_SECRET'] %>
  oauth2_redirect_uri: <%= ENV['WECHAT_APP_NAME_OAUTH2_REDIRECT_URI'] %>
